# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
- name: tf_folder
  value: $(System.DefualtWorkingDirectory)/modules/main_module

pool:
   vmImage: ubuntu-latest

steps:
- script: | 
     docker run --tty --volume $(tf_folder):/tf bridgecrew/checkov --directory /tf --compact
  displayName: Running Checkov












# pool:
#   vmImage: ubuntu-latest

# steps:
# - script: echo Hello, world!
#   displayName: 'Run a one-line script'
# - task: CmdLine@2
#   displayName: Installing Checkov
#   inputs:
#     script: 'pip3 install checkov'

# - task: CmdLine@2
#   inputs:
#     script: 'checkov --directory ${System.DefaultWorkingDirectory} -o junitxml > ${System.DefaultWorkingDirectory}/result.xml'

# - task: PublishTestResults@2
#   inputs:
#     testResultsFormat: 'JUnit'
#     testResultsFiles: 'result.xml'