version: '2.1'
orbs:
  terraform: circleci/terraform@3.0.0
workflows:
  deploy_infra:
    jobs:
      # working_directory: "~/DynamoDB"
      - terraform/validate:
          checkout: true
          context: aws
      - terraform/plan: 
          checkout: true
          context: aws
          persist-workspace: true
          requires:
          - terraform/validate
      # - terraform/apply:
      #     attach-workspace: true
      #     context: aws
      #     filters:
      #       branches:
      #         only: master
      #     requires:
      #     - terraform/plan
      - terraform/destroy:
          attach-workspace: true
          context: aws
          filters:
            branches:
              only: master
          requires:
          - terraform/plan