version: 2
jobs:
  plan:
    docker:
      - image: hashicorp/terraform:latest
    working_directory: /DynamoDB
    steps:
      - checkout
      - run:
          name: Init
          command: terraform init -input=false
      - run:
          name: Plan
          command: terraform plan
          
      - persist_to_workspace:
          root: /DynamoDB
          paths:
            - .

workflows:
  version: 2
  plan_pr:
    jobs:
      - plan
